version = 0.1

[default]
[default.global.parameters]
stack_name = "combustible-stack"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name         = "combustible-stack"
s3_bucket          = ""           # SAM crea/usa bucket propio via --resolve-s3
resolve_s3         = true
region             = "sa-east-1"
confirm_changeset  = false
capabilities       = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"
